### ISSUE TITLE
Breaks (my) repl

### ISSUE THREAD

**Issue by decoursin** [typedclojure/typed-repl#1]
My repl was working fine until I added this:

``` clj
:repl-options {:nrepl-middleware
                       [clojure.core.typed.repl/wrap-clj-repl]}
```

Now, my error is this:

``` clj
REPL-y 0.3.7, nREPL 0.2.10
Clojure 1.7.0
OpenJDK 64-Bit Server VM 1.7.0_79-b14
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (ns ^:core.typed my-ns)
Initializing core.typed ...
Building core.typed base environments ...
Finished building base environments
"Elapsed time: 1033.36803 msecs"
core.typed initialized.
ERROR: Unhandled REPL handler exception processing message {:code (ns ^:core.typed my-ns), :id 6cf350c4-d0af-4605-9c74-2a34060d530d, :op eval, :session 2f60f7e2-3ed5-48f5-bea3-4d4b4811cc4c}
java.lang.NoClassDefFoundError: clojure/tools/nrepl/transport/Transport
    at clojure.core.typed.repl$handle_eval.invoke(repl.clj:89)
    at clojure.core.typed.repl$wrap_clj_repl$fn__27725.invoke(repl.clj:192)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__414.invoke(middleware.clj:22)
    at cider.nrepl.middleware.test$wrap_test$fn__8120.invoke(test.clj:201)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__414.invoke(middleware.clj:22)
    at clojure.tools.nrepl.middleware.session$session$fn__729.invoke(session.clj:192)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__414.invoke(middleware.clj:22)
    at cider.nrepl.middleware.classpath$wrap_classpath$fn__2688.invoke(classpath.clj:24)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__414.invoke(middleware.clj:22)
    at cider.nrepl.middleware.debug$wrap_debug$fn__4389.invoke(debug.clj:328)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__414.invoke(middleware.clj:22)
    at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:19)
    at clojure.tools.nrepl.server$handle$fn__798.invoke(server.clj:28)
    at clojure.core$binding_conveyor_fn$fn__4444.invoke(core.clj:1916)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: clojure.tools.nrepl.transport.Transport
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 19 more
```

Here's my profiles.clj:

``` clj
{:user {:plugins [[lein-exec "0.3.5"]
                  [lein-pprint "1.1.1"] ;; lein pprint ;; print project map
                  [lein-ancient "0.6.7"] ;; lein ancient ; Checks for outdated plugins
                  [lein-kibit "0.1.2"] ;; suggests code to be rewritten to be more idiomatic
                  [org.clojure/tools.namespace "0.2.11"] ;;detects changes to source files and reloads the changed files and their dependents in the correct order
                  [cider/cider-nrepl "0.10.0-SNAPSHOT"]]
        :dependencies [[com.cemerick/pomegranate "0.3.0"]]}
 :repl {:plugins []
        :dependencies [[org.clojure/math.numeric-tower "0.0.4"]]}
 :dev  {:plugins []
        :dependencies [[org.clojure/core.typed "0.3.11"]]
        :repl-options {:nrepl-middleware
                       [clojure.core.typed.repl/wrap-clj-repl]}}}
```

Thanks!

**Comment by frenchy64** [comment]
Please submit here: http://dev.clojure.org/jira/browse/CTYP

**Comment by decoursin** [comment]
Submitted. Here's the direct link: http://dev.clojure.org/jira/browse/CTYP-280
